version: '3.6'

services:

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    env_file:
          - .env
    volumes:
      - mysql:/var/lib/mysql
      - dumps:/code/dumps

volumes:
  mysql:
  dumps: